print("SCORE CALCULATOR:\n\n")
a = str(input("Enter your name: "))
b = str(input("Enter your SRN: "))
print("\nEnter your marks according to the given Subject")
c = float(input("Java Technologies: "))
d = float(input("E-Commerce Application: "))
e = float(input("Software Engineering: "))
f = float(input("Software Application Development: "))
g = float(input("VCS: "))
c = float(input("Java Technologies: "))
print("\nAverage Score: ", ((c+d+e+f+g)/5))
