name: Greeter Action
on: [push]
jobs: 
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Wagwan"
      - name: Step 2
        run: echo "This was written by Aashwija"
